### ISSUE TITLE
Fatal error when sending...

### ISSUE THREAD

**Issue by cube60** [stratisproject/Breeze#145]
Using Mac/Sierra and received this error...

System.ArgumentException: An item with the same key has already been added. Key: OP_DUP OP_HASH160 112305fc04f8f8de8e96c00933c57eed45a64494 OP_EQUALVERIFY OP_CHECKSIG
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Stratis.Bitcoin.Wallet.WalletManager.LoadKeysLookup() in /Users/pieterjan/Desktop/StratisBitcoinFullNode/Stratis.Bitcoin/Wallet/WalletManager.cs:line 1049
   at Stratis.Bitcoin.Wallet.WalletManager.AddTransactionToWallet(uint256 transactionHash, UInt32 time, Nullable`1 index, Money amount, Script script, Nullable`1 blockHeight, Block block) in /Users/pieterjan/Desktop/StratisBitcoinFullNode/Stratis.Bitcoin/Wallet/WalletManager.cs:line 763
   at Stratis.Bitcoin.Wallet.WalletManager.ProcessTransaction(Transaction transaction, Nullable`1 blockHeight, Block block) in /Users/pieterjan/Desktop/StratisBitcoinFullNode/Stratis.Bitcoin/Wallet/WalletManager.cs:line 658
   at Stratis.Bitcoin.Wallet.WalletManager.SendTransaction(String transactionHex) in /Users/pieterjan/Desktop/StratisBitcoinFullNode/Stratis.Bitcoin/Wallet/WalletManager.cs:line 580
   at Stratis.Bitcoin.Wallet.Controllers.WalletController.SendTransaction(SendTransactionRequest request) in /Users/pieterjan/Desktop/StratisBitcoinFullNode/Stratis.Bitcoin/Wallet/Controllers/WalletController.cs:line 459

**Comment by bokobza** [comment]
Added to Trello

**Comment by bokobza** [comment]
Thanks for the feedback @cube60

**Comment by bokobza** [comment]
This happens when an HdAddress SciptPubKey and PubKey are the same. 
Unfortunately I couldn't find an execution path where this could occur.
It might have been fixed by commit https://github.com/stratisproject/StratisBitcoinFullNode/commit/893053b43a16ac3217d662dcc3e3fd963755321f. 
Closing as non-repro.
